import React from "react";
import Head from "next/head";
import Rules from "./Rules";

const Layout = ({ children }: any): JSX.Element => {
  return (
    <>
      <Head>
        <title>Piedra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <main className="bg-gradient-to-r from-indigo-900 to-blue-800 min-h-screen w-full p-1 relative">
        <div className="container mx-auto w-10/12 md:w-8/12 mt-7">
          {children}
        </div>
        <Rules />
      </main>
    </>
  );
};

export default Layout;
