import React, { useCallback, useContext, useEffect } from "react";
import Head from "next/head";

import Rules from "./Rules";
import ApiContext from "../context/api/ApiContext";
import ViewTopPlayers from "./ViewTopPlayers";
import ScoreContext from "../context/score/ScoreContext";
import InfoUser from "./InfoUser";

const Layout = ({ children }: any): JSX.Element => {
  const { getTop, updateScoreUser, user } = useContext(ApiContext);
  const { scoreUser } = useContext(ScoreContext);

  const data = useCallback(() => {
    getTop();
  }, [getTop]);

  useEffect(() => {
    data();
  }, [data]);

  useEffect(() => {
    if (user) {
      if (scoreUser.toString() > user.puntaje) {
        updateScoreUser(user.uid, scoreUser.toString());
      }
    }
  }, [scoreUser, updateScoreUser, user]);

  return (
    <>
      <Head>
        <title>Piedra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <main className="bg-gradient-to-r from-indigo-900 to-blue-800 min-h-screen w-full p-1 relative">
        <div className="container mx-auto w-10/12 md:w-8/12 mt-2">
          <InfoUser />
          {children}
        </div>
        <Rules />
        <ViewTopPlayers />
      </main>
    </>
  );
};

export default Layout;
